---
become_override: false
ocp_username: wkulhane-redhat.com
silent: false

# If your workload needs customization options provide variables to be used.
# Variable names must be prefixed by the role name "<role name>_<variable>".
# So because this example workload is called "ocp4_workload_example" the variables
# should be named "ocp4_workload_example_dedicated_cluster_variable".
#
# You can override the defaults as parameters to the Ansible run that runs
# your workload.

ocp4_workload_feast_example_namespace: "ocp4-workload-feast"
